### ISSUE TITLE
Calling needs :cxx11 is disabled! There is no replacement

### ISSUE THREAD

**Issue by seenyea** [omnisci/mapd-core#321] opened 2019-02-14 03:07 UTC
Macos version: 10.14.2 (18C54)

Homebrew 2.0.1-41-gff898bc
Homebrew/homebrew-core (git revision c0b41; last commit 2019-02-13)
Homebrew/homebrew-cask (git revision d9580; last commit 2019-02-13)

''mapd-deps-osx.sh" in the scripts folder

brew install -s ../ThirdParty/Arrow/apache-arrow.rb 
Error: Calling needs :cxx11 is disabled! There is no replacement.

**Comment by seenyea** [comment] 2019-02-14 03:13
m

**Comment by seenyea** [comment] 2019-02-14 03:15
Macos version: 10.14.2 (18C54)

Homebrew 2.0.1-41-gff898bc
Homebrew/homebrew-core (git revision c0b41; last commit 2019-02-13)
Homebrew/homebrew-cask (git revision d9580; last commit 2019-02-13)

**Comment by randyzwitch** [comment] 2019-02-24 17:43
Thanks for reporting @seenyea. I was able to confirm this issue on OSX Mojave. It appears that this is mostly a Homebrew issue:

https://github.com/Homebrew/brew/pull/5599

We'll have to think internally how to fix this, as I suspect the way to solve the issue is to update the Apache Arrow recipe in Homebrew.

**Comment by randyzwitch** [comment] 2019-02-24 17:52
As it turns out, I didn't realize we keep the Arrow recipe local in our repo. The fix for this is to comment out the line as shown in #325, which we'll merge in shortly. But if you're in a hurry, you could do it yourself while the PR is open.

**Comment by fleapapa** [comment] 2019-02-25 16:23
Not quite following this issue,,, if c++11 is disabled, how can mapd-core be built when it needs c++14? 

BTW, S3 SDK needs c++14, too.

**Comment by randyzwitch** [comment] 2019-02-25 16:25
It's not disabled, I guess they just changed how their recipes are parsed. So you remove that parameter and the package now seems to install correctly (at least on Mojave). Just didn't want to merge it without someone testing on Sierra/High Sierra.

**Closed** 2019-03-02 17:15 UTC
