### ISSUE TITLE
[feature] Deploy JDBC driver into public maven repository

### ISSUE THREAD

**Issue by archenroot** [omnisci/mapd-core#317] opened 2019-02-01 04:12 UTC
Any roadmap on this?

**Comment by archenroot** [comment] 2019-02-01 04:14
Related to: https://github.com/dbeaver/dbeaver/issues/4925

**Comment by randyzwitch** [comment] 2019-02-01 13:32
Duplicate of https://github.com/omnisci/mapd-core/issues/71

We are evaluating what it would take for us to separate the Java code from this repo and to deploy to Maven as part of our build process, but there is no timetable in place. Unfortunately, due to some issues around making Thrift versions match perfectly between all of our various modules and connector packages, this isn't as easy as just doing it real quick and making it happen

**Closed by randyzwitch** 2019-02-01 13:32 UTC

**Comment by jdaviestx** [comment] 2019-04-18 21:43
Any update on this?  It looks like this issue has been floating around for a couple of years now...

**Comment by Smyatkin-Maxim** [comment] 2019-04-19 07:07
@jdaviestx yep, there is an update. It has been prioritized and taken into development recently.

**Comment by archenroot** [comment] 2019-05-09 05:53
@Smyatkin-Maxim - good to know.

**Comment by archenroot** [comment] 2019-05-09 06:03
@randyzwitch - so support for mapd in dbeaver has been added - https://github.com/dbeaver/dbeaver/releases/tag/5.3.4

When maven JDBC driver is available separately it will be automated to package within.
