### ISSUE TITLE
Performance issue with Arrow formatted query output

### ISSUE THREAD

**Issue by sklam** [omnisci/mapd-core#69] opened 2017-09-11 23:14 UTC
Fetching large dataframe with `.select_ipc_gpu` and `.select_ipc` is currently slower than reading from disk with pandas.

I have prepared a notebook to demonstrate the issue: https://gist.github.com/sklam/4ae805c40abc3547b14719438f3c2846).  A `.select_ipc_gpu` takes 3mins while `pandas.readcsv` takes 49s.  The result is obtained on a Ubuntu16.04 with mapd 3.2.3dev.  GPU is GTX 1080.

On a separate profiling run with `nvprof`, I notice a large gap between a device->host and a host->device transfer.  It seems that the resultset is transferred back to the host for some processing and then copied back to the device.  Please see profile result in [query1](https://gist.github.com/sklam/ea3885ac165632af66ba00c48c227668#file-mapd_2query_nvprof_result-txt-L18-L19) and [query2](https://gist.github.com/sklam/ea3885ac165632af66ba00c48c227668#file-mapd_2query_nvprof_result-txt-L35-L36) and their corresponding queries are in cell 3 & 5 of [this notebok](https://gist.github.com/sklam/ea3885ac165632af66ba00c48c227668#file-pymapd_test_profile-ipynb).

**Comment by billmaimone** [comment] 2017-09-12 04:14
@andrewseidl @asuhan @m1mc Is this CPU reduction?

**Comment by asuhan** [comment] 2017-09-12 04:16
You mean conversion. Could be both that or the Python connector itself, I'll try to have a look this week.

**Comment by m1mc** [comment] 2017-09-12 04:27
Likely to be CPU serialization perf issue again.

**Comment by billmaimone** [comment] 2017-09-12 18:59
@asuhan It'd be useful to know in whose component something might be done, so they can take ownership to drive.  Could be python connector, maybe MapD, maybe Arrow, thrift, who knows...

**Comment by randyzwitch** [comment] 2019-04-11 19:20
I'm close this issue, one because it's so old (i.e. much has changed since MapD 3.2.3 and whatever version of pymapd this was) and two because I can't reproduce:

pymapd 0.10 and OmniSci 4.7-dev on Ubuntu 18.04LTS with 1080ti:

- 13.3s for `select_ipc_gpu`
- 14s for `select_ipc`
- 53s for `execute`
- 10.6s for `pandas.read_csv`

So this is something for us to keep an eye on, but at least right now, appears not to be an issue.

**Closed by randyzwitch** 2019-04-11 19:20 UTC
Labels: apache arrow
